import type { SystemsContent } from './en'

export const systemsDe: SystemsContent = {
  pathcore: {
    core: { label: 'PathCore', desc: 'Selbstheilender hexagonaler Kern — Core, Uncore, Un-uncore' },
    mindview: { label: 'MindView', desc: 'Eine lebende Karte des Systems, in Echtzeit gestreamt' },
    cog: { label: 'Kognitive Worker', desc: 'KI-Worker stellen die Diagnose und schlagen die Lösung vor' },
    chaos: { label: 'Chaos-Engine', desc: 'Erzeugt Ausfälle mit Absicht, damit Erholung geübt bleibt' },
    breakers: { label: 'Schutzschalter', desc: 'Isolieren einen fehlerhaften Pfad, bevor er sich ausbreitet' },
    deploy: { label: 'Deploy-Executor', desc: 'Ausfallbewusste Deploys mit automatischem Rollback' },
    mergeq: { label: 'Merge-Queue', desc: 'Führt Änderungen in sicherer Reihenfolge zusammen' },
    jobs: { label: 'Job-Flotte', desc: 'Hintergrund-Jobs mit priorisierter Planung' },
    queue: { label: 'Job-Queue', desc: 'Dauerhafte Queue — jede Arbeit bleibt wiederholbar' },
    auth: { label: 'Auth', desc: 'Identität und Zugriff, eine Schicht für jeden Dienst' },
    storage: { label: 'Speicher', desc: 'Objekt- und Zustandsspeicher für die ganze Flotte' },
    events: { label: 'Event-Stream', desc: 'Jede Zustandsänderung wird als Live-Event publiziert' },
    aigw: { label: 'KI-Gateway', desc: 'Eine kontrollierte Tür zu den Sprachmodellen' },
  },

  videolinker: {
    core: { label: 'VideoLinker', desc: 'KI-orchestrierte Plattform für Videoproduktion' },
    canvas: { label: 'Canvas-App', desc: 'Unendliche Leinwand mit KI-Befehlszeile' },
    api: { label: 'Kern-API', desc: '30 Router, mandantenfähig, Fortschritt live' },
    fleet: { label: 'Task-Flotte', desc: '38 Hintergrund-Tasks: erzeugen, rendern, veröffentlichen' },
    pipeline: { label: 'Pipeline', desc: '11 Schritte in Reihe: Serienbibel → Endschnitt' },
    script: { label: 'Drehbuch-Engine', desc: 'Serienbibel, Episoden, Drehbücher, Auflösung in Shots' },
    qa: { label: 'QA-Engine', desc: '60+ gewichtete Regeln bewerten jede Episode von 0 bis 100' },
    keyframes: { label: 'Keyframe-Gen', desc: 'Shot-Keyframes über mehrere Bildmodelle hinweg' },
    videogen: { label: 'Video-Gen', desc: 'Clips aus Bildern, über mehrere Anbieter' },
    tts: { label: 'Stimme & TTS', desc: 'Erzählstimme, geklont, mit ruhig geführtem Tempo' },
    captions: { label: 'Untertitel', desc: 'Timing pro Wort, gestaltet und fest eingebrannt' },
    compose: { label: 'Komposition', desc: 'FFmpeg-Montage: Übergänge, Overlays, SFX-Mix' },
    gpu: { label: 'GPU-Upscaler', desc: 'Eigener GPU-Container für das Hochskalieren der Frames' },
    agent: { label: 'Agenten-Loop', desc: 'Ein autonomer Agent plant und ruft 59 Werkzeuge auf' },
    tools: { label: 'Werkzeugschicht', desc: '12 Tool-Server, die ein Agentenprotokoll sprechen' },
    store: { label: 'Artefaktspeicher', desc: 'Inhaltsadressierte Artefakte, per Hash entdoppelt' },
  },

  frontdesk: {
    core: { label: 'FrontDesk', desc: 'Der Preis von Rang — belegt, datiert, überprüfbar' },
    radar: { label: 'Entdeckungsradar', desc: 'Erkennt wirklich neue Produkte und echte Nachfrage' },
    harvest: { label: 'Sammel-Agenten', desc: 'Schreibende Agenten tragen Fakten aus Quellen zusammen' },
    verifier: { label: 'Gegen-Prüfer', desc: 'Ein zweiter Agent versucht, jede Aussage zu widerlegen' },
    fidelity: { label: 'Treue-Gate', desc: 'Holt jede Quelle erneut; unbelegte Zahlen erscheinen nie' },
    corpus: { label: 'Korpus', desc: '4.400+ Einträge; jeder Preis trägt Quelle und Datum' },
    truth: { label: 'Wahrheitskern', desc: 'Event-basierte Datenbank als Rückgrat des Korpus' },
    pricescan: { label: 'Preis-Scan', desc: 'Täglicher Abgleich ohne KI, mit vier Prüfungen vorab' },
    history: { label: 'Preisverlauf', desc: 'Nur-anhängen-Verlauf mit archivischer Nachbefüllung' },
    ledger: { label: 'Hash-Register', desc: 'SHA-256-Kette — Geschichte lässt sich nicht umschreiben' },
    sitegen: { label: 'Seitengenerator', desc: '23.000+ zitierfähige statische Seiten aus dem Korpus' },
    index: { label: 'Index-Engine', desc: 'Sofortige Indexierung, Markup, fertige Antworten' },
    mcp: { label: 'MCP-Server', desc: '19 Werkzeuge liefern KI-Agenten den belegten Stand' },
    feeds: { label: 'Maschinen-Feeds', desc: 'llms.txt, offene Dumps, Belege jeder Prüfung' },
    mirror: { label: 'Offener Spiegel', desc: 'CC-BY-Korpus in offenen Datensätzen, samt DOI' },
    imgcdn: { label: 'Bild-CDN', desc: 'Lizenzierte Bilder aus privatem Ursprung, am Rand gecacht' },
    extension: { label: 'Erweiterung', desc: 'Der Preis von Rang direkt über der Shop-Seite' },
  },

  relocating: {
    core: { label: 'Relocating', desc: 'Offene Daten, zu einem Umzugsprodukt geformt' },
    etl: { label: 'Open-Data-ETL', desc: 'Weltbank, Wetter, Geo — pro Land normalisiert' },
    datasets: { label: 'Datensatzkern', desc: '30+ Datensätze über 50 Länder hinweg' },
    quality: { label: 'Qualitäts-Gate', desc: 'Schlechte Daten lassen den Build scheitern — wörtlich' },
    pages: { label: 'Seiten-Engine', desc: 'Programmatische Korridore, Vergleiche und Ranglisten' },
    tools: { label: 'Rechner-Suite', desc: '33 Rechner, alle laufen im Browser' },
    build: { label: 'Statischer Build', desc: 'Alles vorgebaut — zur Laufzeit kann nichts kaputtgehen' },
    i18n: { label: 'i18n-Pipeline', desc: 'Spiegelt die ganze Site in 22 Sprachen' },
    tm: { label: 'Übersetzungsspeicher', desc: 'Versionierter Cache — kein Deploy ruft eine Live-Übersetzung' },
    mt: { label: 'MT-Engine', desc: 'Selbst gehostete Übersetzungsmodelle, GPU-Durchläufe' },
    discovery: { label: 'KI-Auffindbarkeit', desc: 'llms.txt und Markup — gebaut, um zitiert zu werden' },
    edge: { label: 'Edge-Auslieferung', desc: 'Statisch am Rand, Auto-TLS, unveränderliches Caching' },
    chat: { label: 'Stadt-Chat', desc: 'Echtzeit-Räume mit Präsenz, aus Daten befüllt' },
    mod: { label: 'KI-Moderation', desc: 'Ein Modell prüft jede Nachricht, bevor sie öffentlich wird' },
    safety: { label: 'Sicherheit', desc: 'Sperren, Audit-Log, Limits, Aufbewahrung nach DSGVO' },
    db: { label: 'EU-Postgres', desc: 'Row-Level-Security überall, so wenig PII wie möglich' },
  },

  studio: {
    core: 'Autofract',
    pathcore: 'PathCore',
    videolinker: 'VideoLinker',
    frontdesk: 'FrontDesk',
    relocating: 'Relocating',
    agents: 'KI-Agenten',
    gates: 'QA-Gates',
    pipelines: 'Pipelines',
    edge: 'Edge',
    healing: 'Selbstheilung',
    data: 'Offene Daten',
  },
}
