import type { SystemsContent } from './en'

export const systemsEs: SystemsContent = {
  pathcore: {
    core: { label: 'PathCore', desc: 'Núcleo hexagonal que se cura solo — Core, Uncore, Un-uncore' },
    mindview: { label: 'MindView', desc: 'Un mapa vivo de todo el sistema, en tiempo real' },
    cog: { label: 'Trabajadores cognitivos', desc: 'Agentes de IA que diagnostican fallos y proponen el arreglo' },
    chaos: { label: 'Motor de caos', desc: 'Provoca fallos a propósito para que la recuperación no se oxide' },
    breakers: { label: 'Cortacircuitos', desc: 'Aíslan la ruta que falla antes de que se propague' },
    deploy: { label: 'Ejecutor de despliegue', desc: 'Despliegues conscientes del fallo, con reversión automática' },
    mergeq: { label: 'Cola de fusión', desc: 'Integra los cambios en un orden seguro' },
    jobs: { label: 'Flota de tareas', desc: 'Tareas en segundo plano con planificación por prioridad' },
    queue: { label: 'Cola de trabajos', desc: 'Cola duradera: cualquier trabajo se puede repetir' },
    auth: { label: 'Autenticación', desc: 'Identidad y acceso, una sola capa para cada servicio' },
    storage: { label: 'Almacenamiento', desc: 'Objetos y estado compartidos por toda la flota' },
    events: { label: 'Flujo de eventos', desc: 'Cada cambio de estado se publica como evento en vivo' },
    aigw: { label: 'Pasarela de IA', desc: 'Una única puerta controlada a los modelos de lenguaje' },
  },

  videolinker: {
    core: { label: 'VideoLinker', desc: 'Plataforma de producción de vídeo orquestada por IA' },
    canvas: { label: 'App de lienzo', desc: 'Estudio de lienzo infinito con barra de intención por IA' },
    api: { label: 'API central', desc: '30 enrutadores, multiinquilino, progreso en vivo' },
    fleet: { label: 'Flota de tareas', desc: '38 tareas de fondo: generar, renderizar, publicar' },
    pipeline: { label: 'Cadena', desc: '11 pasos en orden: biblia de la serie → corte final' },
    script: { label: 'Motor de guion', desc: 'Biblia, episodios, guiones y desglose de planos' },
    qa: { label: 'Motor de QA', desc: '60+ reglas ponderadas puntúan cada episodio de 0 a 100' },
    keyframes: { label: 'Fotogramas clave', desc: 'Fotogramas de plano en varios modelos de imagen' },
    videogen: { label: 'Generación de vídeo', desc: 'Clips de imagen a vídeo con varios proveedores' },
    tts: { label: 'Voz y TTS', desc: 'Narración con voces clonadas y ritmo medido' },
    captions: { label: 'Subtítulos', desc: 'Tiempos palabra a palabra, con estilo e incrustados' },
    compose: { label: 'Composición', desc: 'Montaje en FFmpeg: transiciones, capas y mezcla de efectos' },
    gpu: { label: 'Escalador GPU', desc: 'Contenedor GPU dedicado a escalar los fotogramas' },
    agent: { label: 'Bucle del agente', desc: 'Un agente autónomo planifica y llama a 59 herramientas' },
    tools: { label: 'Capa de herramientas', desc: '12 servidores que hablan un mismo protocolo de agente' },
    store: { label: 'Almacén de artefactos', desc: 'Artefactos direccionados por contenido, sin duplicados' },
  },

  frontdesk: {
    core: { label: 'FrontDesk', desc: 'El precio de referencia: con fuente, fecha y verificación' },
    radar: { label: 'Radar de novedades', desc: 'Detecta productos realmente nuevos y demanda real' },
    harvest: { label: 'Agentes recolectores', desc: 'Agentes redactores reúnen hechos de fuentes publicadas' },
    verifier: { label: 'Verificador adversario', desc: 'Un segundo agente intenta refutar cada afirmación' },
    fidelity: { label: 'Filtro de fidelidad', desc: 'Revisita cada fuente: ningún dato sin prueba se publica' },
    corpus: { label: 'Corpus', desc: '4.400+ entidades; cada precio lleva fuente y fecha' },
    truth: { label: 'Núcleo de verdad', desc: 'Base de datos por eventos que sostiene todo el corpus' },
    pricescan: { label: 'Escaneo de precios', desc: 'Rastreo diario sin IA y cuatro guardas antes de escribir' },
    history: { label: 'Historial de precios', desc: 'Registro que solo añade, con relleno desde el archivo' },
    ledger: { label: 'Registro hash', desc: 'Cadena SHA-256: la historia ya no se puede reescribir' },
    sitegen: { label: 'Generador del sitio', desc: '23.000+ páginas estáticas citables salidas del corpus' },
    index: { label: 'Motor de índice', desc: 'Indexación instantánea, datos estructurados y respuestas' },
    mcp: { label: 'Servidor MCP', desc: '19 herramientas sirven el registro con fuentes a las IA' },
    feeds: { label: 'Feeds para máquinas', desc: 'llms.txt, volcados abiertos y recibos de verificación' },
    mirror: { label: 'Espejo abierto', desc: 'Corpus CC-BY replicado en datasets abiertos, con DOI' },
    imgcdn: { label: 'CDN de imágenes', desc: 'Imágenes con licencia desde origen privado, en la caché' },
    extension: { label: 'Extensión', desc: 'El precio de referencia sobre la página de la tienda' },
  },

  relocating: {
    core: { label: 'Relocating', desc: 'Datos abiertos convertidos en un producto de mudanza' },
    etl: { label: 'ETL de datos abiertos', desc: 'Banco Mundial, clima y geo, normalizados por país' },
    datasets: { label: 'Núcleo de datos', desc: '30+ conjuntos de datos que cubren 50 países' },
    quality: { label: 'Filtro de calidad', desc: 'Un dato malo tumba la compilación — literalmente' },
    pages: { label: 'Motor de páginas', desc: 'Corredores, comparativas y rankings generados' },
    tools: { label: 'Suite de calculadoras', desc: '33 calculadoras, todas funcionan en tu navegador' },
    build: { label: 'Compilación estática', desc: 'Todo prehecho: no hay servidor que se caiga' },
    i18n: { label: 'Cadena i18n', desc: 'Replica el sitio entero en 22 idiomas' },
    tm: { label: 'Memoria de traducción', desc: 'Caché versionada: ningún despliegue traduce en vivo' },
    mt: { label: 'Motor de traducción', desc: 'Modelos de traducción propios, pasadas en GPU' },
    discovery: { label: 'Descubrimiento por IA', desc: 'llms.txt y marcado: hecho para que lo citen' },
    edge: { label: 'Entrega en el borde', desc: 'Estático en el borde, TLS automático, caché inmutable' },
    chat: { label: 'Chat de ciudad', desc: 'Salas en vivo con presencia, sembradas con datos' },
    mod: { label: 'Moderación por IA', desc: 'Un modelo revisa cada mensaje antes de hacerse público' },
    safety: { label: 'Confianza y seguridad', desc: 'Bloqueos, registro de auditoría, límites y RGPD' },
    db: { label: 'Postgres en la UE', desc: 'Seguridad por fila en todo, con datos personales mínimos' },
  },

  studio: {
    core: 'Autofract',
    pathcore: 'PathCore',
    videolinker: 'VideoLinker',
    frontdesk: 'FrontDesk',
    relocating: 'Relocating',
    agents: 'Agentes de IA',
    gates: 'Filtros de QA',
    pipelines: 'Cadenas',
    edge: 'Borde',
    healing: 'Autocuración',
    data: 'Datos abiertos',
  },
}
