import type { SystemsContent } from './en'

export const systemsFr: SystemsContent = {
  pathcore: {
    core: { label: 'PathCore', desc: 'Cœur hexagonal qui se répare seul — Core, Uncore, Un-uncore' },
    mindview: { label: 'MindView', desc: 'Une carte vivante de tout le système, diffusée en direct' },
    cog: { label: 'Workers cognitifs', desc: 'Des agents IA diagnostiquent la panne et proposent le correctif' },
    chaos: { label: 'Moteur de chaos', desc: 'Provoque des pannes exprès pour que la reprise reste entraînée' },
    breakers: { label: 'Disjoncteurs', desc: 'Isolent le chemin défaillant avant qu’il ne se propage' },
    deploy: { label: 'Exécuteur de déploiement', desc: 'Déploiements conscients des pannes, retour arrière automatique' },
    mergeq: { label: 'File de fusion', desc: 'Intègre les changements dans un ordre sûr' },
    jobs: { label: 'Flotte de jobs', desc: 'Tâches de fond avec ordonnancement par priorité' },
    queue: { label: 'File d’attente', desc: 'File durable : tout travail reste rejouable' },
    auth: { label: 'Authentification', desc: 'Identité et accès, une seule couche pour chaque service' },
    storage: { label: 'Stockage', desc: 'Objets et états partagés par toute la flotte' },
    events: { label: 'Flux d’événements', desc: 'Chaque changement d’état publié comme événement en direct' },
    aigw: { label: 'Passerelle IA', desc: 'Une seule porte contrôlée vers les modèles de langage' },
  },

  videolinker: {
    core: { label: 'VideoLinker', desc: 'Plateforme de production vidéo orchestrée par l’IA' },
    canvas: { label: 'App toile', desc: 'Studio à toile infinie avec une barre d’intention IA' },
    api: { label: 'API centrale', desc: '30 routeurs, multi-locataire, progression en direct' },
    fleet: { label: 'Flotte de tâches', desc: '38 tâches de fond : générer, rendre, publier' },
    pipeline: { label: 'Chaîne', desc: '11 étapes ordonnées : bible de série → montage final' },
    script: { label: 'Moteur de script', desc: 'Bible, épisodes, scripts et découpage en plans' },
    qa: { label: 'Moteur QA', desc: '60+ règles pondérées notent chaque épisode de 0 à 100' },
    keyframes: { label: 'Images-clés', desc: 'Images-clés de plan sur plusieurs modèles d’image' },
    videogen: { label: 'Génération vidéo', desc: 'Clips image-vers-vidéo chez plusieurs fournisseurs' },
    tts: { label: 'Voix et TTS', desc: 'Narration en voix clonée, au rythme maîtrisé' },
    captions: { label: 'Sous-titres', desc: 'Minutage au mot, stylés et incrustés à l’image' },
    compose: { label: 'Composition', desc: 'Montage FFmpeg : transitions, calques, mixage des bruitages' },
    gpu: { label: 'Upscaler GPU', desc: 'Conteneur GPU dédié à l’agrandissement des images' },
    agent: { label: 'Boucle d’agent', desc: 'Un agent autonome planifie et appelle 59 outils' },
    tools: { label: 'Couche d’outils', desc: '12 serveurs d’outils parlant un seul protocole d’agent' },
    store: { label: 'Dépôt d’artefacts', desc: 'Artefacts adressés par contenu, dédoublonnés par hachage' },
  },

  frontdesk: {
    core: { label: 'FrontDesk', desc: 'Le prix de référence : sourcé, daté, vérifiable' },
    radar: { label: 'Radar de nouveautés', desc: 'Repère les produits vraiment nouveaux et la demande réelle' },
    harvest: { label: 'Agents collecteurs', desc: 'Des agents rédacteurs compilent les faits publiés' },
    verifier: { label: 'Vérificateur adverse', desc: 'Un second agent cherche à réfuter chaque affirmation' },
    fidelity: { label: 'Filtre de fidélité', desc: 'Recharge chaque source ; aucun chiffre non prouvé ne passe' },
    corpus: { label: 'Corpus', desc: '4 400+ entités ; chaque prix porte sa source et sa date' },
    truth: { label: 'Noyau de vérité', desc: 'Base événementielle, colonne vertébrale du corpus' },
    pricescan: { label: 'Scan des prix', desc: 'Relevé quotidien sans IA et quatre garde-fous avant écriture' },
    history: { label: 'Historique des prix', desc: 'Journal en ajout seul, complété depuis les archives' },
    ledger: { label: 'Registre de hachage', desc: 'Chaîne SHA-256 : l’histoire ne se réécrit pas' },
    sitegen: { label: 'Générateur de site', desc: '23 000+ pages statiques citables issues du corpus' },
    index: { label: 'Moteur d’index', desc: 'Indexation immédiate, données structurées, réponses prêtes' },
    mcp: { label: 'Serveur MCP', desc: '19 outils servent aux agents IA le relevé sourcé' },
    feeds: { label: 'Flux machines', desc: 'llms.txt, exports ouverts, reçus de vérification' },
    mirror: { label: 'Miroir ouvert', desc: 'Corpus CC-BY répliqué en jeux de données ouverts, avec DOI' },
    imgcdn: { label: 'CDN d’images', desc: 'Images sous licence depuis une origine privée, mises en cache' },
    extension: { label: 'Extension', desc: 'Le prix de référence affiché sur la page du marchand' },
  },

  relocating: {
    core: { label: 'Relocating', desc: 'Des données ouvertes transformées en produit d’expatriation' },
    etl: { label: 'ETL open data', desc: 'Banque mondiale, météo, géo — normalisés par pays' },
    datasets: { label: 'Noyau de données', desc: '30+ jeux de données couvrant 50 pays' },
    quality: { label: 'Filtre qualité', desc: 'Une donnée fausse fait échouer le build — littéralement' },
    pages: { label: 'Moteur de pages', desc: 'Corridors, comparatifs et classements générés' },
    tools: { label: 'Suite de calculateurs', desc: '33 calculateurs, tous exécutés dans le navigateur' },
    build: { label: 'Build statique', desc: 'Tout est prégénéré : aucun serveur à faire tomber' },
    i18n: { label: 'Chaîne i18n', desc: 'Duplique le site entier en 22 langues' },
    tm: { label: 'Mémoire de traduction', desc: 'Cache versionné : aucun déploiement ne traduit en direct' },
    mt: { label: 'Moteur de traduction', desc: 'Modèles de traduction auto-hébergés, passes GPU' },
    discovery: { label: 'Découverte par l’IA', desc: 'llms.txt et balisage : conçu pour être cité' },
    edge: { label: 'Diffusion en périphérie', desc: 'Statique en périphérie, TLS auto, cache immuable' },
    chat: { label: 'Chat de ville', desc: 'Salons en direct avec présence, amorcés par les données' },
    mod: { label: 'Modération IA', desc: 'Un modèle relit chaque message avant sa publication' },
    safety: { label: 'Confiance et sécurité', desc: 'Bannissements, journal d’audit, quotas, rétention RGPD' },
    db: { label: 'Postgres en UE', desc: 'Sécurité par ligne partout, données personnelles réduites' },
  },

  studio: {
    core: 'Autofract',
    pathcore: 'PathCore',
    videolinker: 'VideoLinker',
    frontdesk: 'FrontDesk',
    relocating: 'Relocating',
    agents: 'Agents IA',
    gates: 'Filtres QA',
    pipelines: 'Chaînes',
    edge: 'Périphérie',
    healing: 'Auto-réparation',
    data: 'Données ouvertes',
  },
}
