import type { SystemsContent } from './en'

export const systemsPt: SystemsContent = {
  pathcore: {
    core: { label: 'PathCore', desc: 'Núcleo hexagonal que se cura sozinho — Core, Uncore, Un-uncore' },
    mindview: { label: 'MindView', desc: 'Um mapa vivo do sistema inteiro, transmitido em tempo real' },
    cog: { label: 'Workers cognitivos', desc: 'Agentes de IA diagnosticam a falha e propõem a correção' },
    chaos: { label: 'Motor de caos', desc: 'Provoca falhas de propósito para a recuperação não enferrujar' },
    breakers: { label: 'Disjuntores', desc: 'Isolam o caminho com falha antes que ela se espalhe' },
    deploy: { label: 'Executor de deploy', desc: 'Deploys cientes de falha, com reversão automática' },
    mergeq: { label: 'Fila de merge', desc: 'Integra as mudanças em uma ordem segura' },
    jobs: { label: 'Frota de jobs', desc: 'Tarefas em segundo plano com fila por prioridade' },
    queue: { label: 'Fila de trabalhos', desc: 'Fila durável: todo trabalho continua repetível' },
    auth: { label: 'Autenticação', desc: 'Identidade e acesso, uma camada para cada serviço' },
    storage: { label: 'Armazenamento', desc: 'Objetos e estado compartilhados por toda a frota' },
    events: { label: 'Fluxo de eventos', desc: 'Toda mudança de estado publicada como evento ao vivo' },
    aigw: { label: 'Gateway de IA', desc: 'Uma única porta controlada para os modelos de linguagem' },
  },

  videolinker: {
    core: { label: 'VideoLinker', desc: 'Plataforma de produção de vídeo orquestrada por IA' },
    canvas: { label: 'App de tela', desc: 'Estúdio de tela infinita com barra de intenção por IA' },
    api: { label: 'API central', desc: '30 roteadores, multi-inquilino, progresso ao vivo' },
    fleet: { label: 'Frota de tarefas', desc: '38 tarefas de fundo: gerar, renderizar, publicar' },
    pipeline: { label: 'Esteira', desc: '11 etapas em ordem: bíblia da série → corte final' },
    script: { label: 'Motor de roteiro', desc: 'Bíblia, episódios, roteiros e decupagem de planos' },
    qa: { label: 'Motor de QA', desc: '60+ regras ponderadas dão nota de 0 a 100 a cada episódio' },
    keyframes: { label: 'Quadros-chave', desc: 'Quadros-chave de plano em vários modelos de imagem' },
    videogen: { label: 'Geração de vídeo', desc: 'Clipes de imagem para vídeo em vários provedores' },
    tts: { label: 'Voz e TTS', desc: 'Narração com vozes clonadas e ritmo bem medido' },
    captions: { label: 'Legendas', desc: 'Marcação palavra a palavra, estilizada e queimada no vídeo' },
    compose: { label: 'Composição', desc: 'Montagem em FFmpeg: transições, camadas e mixagem de efeitos' },
    gpu: { label: 'Ampliador GPU', desc: 'Contêiner GPU dedicado a ampliar os quadros' },
    agent: { label: 'Laço do agente', desc: 'Um agente autônomo planeja e chama 59 ferramentas' },
    tools: { label: 'Camada de ferramentas', desc: '12 servidores falando um mesmo protocolo de agente' },
    store: { label: 'Depósito de artefatos', desc: 'Artefatos endereçados por conteúdo, sem duplicatas' },
  },

  frontdesk: {
    core: { label: 'FrontDesk', desc: 'O preço de referência: com fonte, data e verificação' },
    radar: { label: 'Radar de novidades', desc: 'Detecta produtos realmente novos e demanda real' },
    harvest: { label: 'Agentes coletores', desc: 'Agentes redatores reúnem fatos de fontes publicadas' },
    verifier: { label: 'Verificador adversário', desc: 'Um segundo agente tenta refutar cada afirmação' },
    fidelity: { label: 'Filtro de fidelidade', desc: 'Rebusca cada fonte; número sem prova nunca é publicado' },
    corpus: { label: 'Corpus', desc: '4.400+ entidades; cada preço traz fonte e data' },
    truth: { label: 'Núcleo de verdade', desc: 'Banco por eventos que sustenta todo o corpus' },
    pricescan: { label: 'Varredura de preços', desc: 'Coleta diária sem IA e quatro travas antes de gravar' },
    history: { label: 'Histórico de preços', desc: 'Registro só de acréscimo, completado a partir do arquivo' },
    ledger: { label: 'Registro hash', desc: 'Cadeia SHA-256: a história não pode ser reescrita' },
    sitegen: { label: 'Gerador do site', desc: '23.000+ páginas estáticas citáveis vindas do corpus' },
    index: { label: 'Motor de índice', desc: 'Indexação instantânea, dados estruturados e respostas' },
    mcp: { label: 'Servidor MCP', desc: '19 ferramentas entregam o registro com fontes às IAs' },
    feeds: { label: 'Feeds para máquinas', desc: 'llms.txt, dumps abertos e recibos de verificação' },
    mirror: { label: 'Espelho aberto', desc: 'Corpus CC-BY espelhado em datasets abertos, com DOI' },
    imgcdn: { label: 'CDN de imagens', desc: 'Imagens licenciadas de origem privada, em cache na borda' },
    extension: { label: 'Extensão', desc: 'O preço de referência sobreposto à página da loja' },
  },

  relocating: {
    core: { label: 'Relocating', desc: 'Dados abertos transformados em um produto de mudança' },
    etl: { label: 'ETL de dados abertos', desc: 'Banco Mundial, clima e geo, normalizados por país' },
    datasets: { label: 'Núcleo de dados', desc: '30+ conjuntos de dados cobrindo 50 países' },
    quality: { label: 'Filtro de qualidade', desc: 'Dado ruim derruba o build — literalmente' },
    pages: { label: 'Motor de páginas', desc: 'Corredores, comparações e rankings gerados' },
    tools: { label: 'Suíte de calculadoras', desc: '33 calculadoras, todas rodando no seu navegador' },
    build: { label: 'Build estático', desc: 'Tudo pronto de antemão: não há servidor para cair' },
    i18n: { label: 'Esteira de i18n', desc: 'Espelha o site inteiro em 22 idiomas' },
    tm: { label: 'Memória de tradução', desc: 'Cache versionado: nenhum deploy traduz ao vivo' },
    mt: { label: 'Motor de tradução', desc: 'Modelos de tradução próprios, passagens em GPU' },
    discovery: { label: 'Descoberta por IA', desc: 'llms.txt e marcação: feito para ser citado' },
    edge: { label: 'Entrega na borda', desc: 'Estático na borda, TLS automático, cache imutável' },
    chat: { label: 'Chat da cidade', desc: 'Salas ao vivo com presença, alimentadas por dados' },
    mod: { label: 'Moderação por IA', desc: 'Um modelo revisa cada mensagem antes de ela ficar pública' },
    safety: { label: 'Confiança e segurança', desc: 'Banimentos, log de auditoria, limites e retenção conforme o GDPR' },
    db: { label: 'Postgres na UE', desc: 'Segurança por linha em tudo, com dados pessoais mínimos' },
  },

  studio: {
    core: 'Autofract',
    pathcore: 'PathCore',
    videolinker: 'VideoLinker',
    frontdesk: 'FrontDesk',
    relocating: 'Relocating',
    agents: 'Agentes de IA',
    gates: 'Filtros de QA',
    pipelines: 'Esteiras',
    edge: 'Borda',
    healing: 'Autocura',
    data: 'Dados abertos',
  },
}
